'use client';
import './globals.css';
import type { Metadata } from 'next';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import Script from 'next/script';
import { StateProvider } from '@/context/StateContext';
import CookieConsent from 'react-cookie-consent';
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import { Suspense, useEffect, useState } from 'react';
import { useRouter, usePathname } from 'next/navigation';
import React from 'react';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Loading from './loading';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const stripePromise = loadStripe(
    process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY as string
  );

  // window width that detects width of screen
  const [width, setWidth] = useState<number>(0);

  // detect width of screen
  useEffect(() => {
    setWidth(window.innerWidth);
  }, []);

  return (
    <html lang="en">
      <StateProvider>
        <CookieConsent
          location="none"
          buttonText="Accept"
          cookieName="myAwesomeCookieName2"
          style={{
            background: '#7F8119',
            color: '#fff !important',
            fontSize: '20px',
            display: 'flex',
            flexDirection: 'column',
            borderRadius: '10px',
            boxShadow: '5px 10px 10px 2px rgba(0, 0, 0, 0.304)',
            flex: 0,
            padding: '20px',
            width: width > 768 ? '60%' : '100%',
            bottom: '0px',
            left: '0',
            right: '0',
            margin: 'auto',
            height: 'fit-content',
            zIndex: 10000000,
            justifyContent: 'center',
          }}
          contentStyle={{
            flex: 0,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            margin: 'auto',
          }}
          buttonClasses="bg-white text-black px-4 py-2 rounded-md m-auto"
          buttonWrapperClasses="flex justify-center w-full mt-4"
          buttonStyle={{
            color: '#4e503b',
            fontSize: '20px',
            alignContent: 'center',
            display: 'flex',
            margin: 'auto',
          }}
          expires={150}>
          <div className="m-auto w-full text-white text-center h-fit flex-none">
            We value your privacy <br />
            <span
              style={{
                fontSize: '16px',
                textAlign: 'left',
                color: 'white',
              }}>
              We use cookies to enhance your experience on our website. By
              continuing to use our website, you consent to the use of cookies.
            </span>
          </div>
        </CookieConsent>
        <Elements stripe={stripePromise}>
          <body className="relative">
            <>
              <Navigation />
              <Suspense fallback={<Loading />}>
                {children}
                <SpeedInsights />
                <Analytics />
              </Suspense>
              <Footer />
              <Script src="https://player.vimeo.com/api/player.js"></Script>
            </>
          </body>
        </Elements>
      </StateProvider>
    </html>
  );
}
