import { defineType } from "sanity";
export default defineType({
  name: 'amenities',
  title: 'Amenities',
  type: 'object',
  fields: [
    { name: 'bike', type: 'boolean', title: 'Bike' },
    { name: 'car', type: 'boolean', title: 'Car' },
    { name: 'tv', type: 'boolean', title: 'TV' },
    { name: 'dishwasher', type: 'boolean', title: 'Dishwasher' },
    { name: 'pingpong', type: 'boolean', title: 'Ping Pong' },
    { name: 'billiards', type: 'boolean', title: 'Billiards' },
    { name: 'washer', type: 'boolean', title: 'Washer' },
    { name: 'dryer', type: 'boolean', title: 'Dryer' },
    { name: 'wifi', type: 'boolean', title: 'Wi-Fi' },
    { name: 'elevator', type: 'boolean', title: 'Elevator' },
    { name: 'terrace', type: 'boolean', title: 'Terrace' },
    { name: 'scooter', type: 'boolean', title: 'Scooter' },
    { name: 'bbq', type: 'boolean', title: 'BBQ' },
    { name: 'computer', type: 'boolean', title: 'Computer' },
    { name: 'wcAccess', type: 'boolean', title: 'Wheelchair Access' },
    { name: 'pool', type: 'boolean', title: 'Pool' },
    { name: 'playground', type: 'boolean', title: 'Playground' },
    { name: 'babyGear', type: 'boolean', title: 'Baby Gear' },
    { name: 'ac', type: 'boolean', title: 'Air Conditioning' },
    { name: 'fireplace', type: 'boolean', title: 'Fireplace' },
    { name: 'parking', type: 'boolean', title: 'Parking' },
    { name: 'hotTub', type: 'boolean', title: 'Hot Tub' },
    { name: 'sauna', type: 'boolean', title: 'Sauna' },
    { name: 'other', type: 'boolean', title: 'Other' },
    { name: 'doorman', type: 'boolean', title: 'Doorman' },
    { name: 'cleaningService', type: 'boolean', title: 'Cleaning Service' },
    { name: 'videoGames', type: 'boolean', title: 'Video Games' },
    { name: 'tennisCourt', type: 'boolean', title: 'Tennis Court' },
    { name: 'gym', type: 'boolean', title: 'Gym' },
  ],
  options: {
    collapsible: true,
    columns: 3,
  }
});
